// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvHy5U7bZ8zXYszvElS_XImImnSGhjJ3Q',
    appId: '1:856901465837:web:5d75da6fc0122e01713ee4',
    messagingSenderId: '856901465837',
    projectId: 'vamonessa-bdcdc',
    authDomain: 'vamonessa-bdcdc.firebaseapp.com',
    databaseURL: 'https://vamonessa-bdcdc-default-rtdb.firebaseio.com',
    storageBucket: 'vamonessa-bdcdc.firebasestorage.app',
    measurementId: 'G-1RMNDEK70V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHZ0gJxfqqpGmoV4K-yg25eDNJA88Vp44',
    appId: '1:856901465837:android:e376309b8577facb713ee4',
    messagingSenderId: '856901465837',
    projectId: 'vamonessa-bdcdc',
    databaseURL: 'https://vamonessa-bdcdc-default-rtdb.firebaseio.com',
    storageBucket: 'vamonessa-bdcdc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByIn4XN9Tx3S08S1F_57MtMI8PGienq6U',
    appId: '1:856901465837:ios:3e2861aed22dbae4713ee4',
    messagingSenderId: '856901465837',
    projectId: 'vamonessa-bdcdc',
    databaseURL: 'https://vamonessa-bdcdc-default-rtdb.firebaseio.com',
    storageBucket: 'vamonessa-bdcdc.firebasestorage.app',
    iosBundleId: 'com.example.vamonessa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByIn4XN9Tx3S08S1F_57MtMI8PGienq6U',
    appId: '1:856901465837:ios:3e2861aed22dbae4713ee4',
    messagingSenderId: '856901465837',
    projectId: 'vamonessa-bdcdc',
    databaseURL: 'https://vamonessa-bdcdc-default-rtdb.firebaseio.com',
    storageBucket: 'vamonessa-bdcdc.firebasestorage.app',
    iosBundleId: 'com.example.vamonessa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvHy5U7bZ8zXYszvElS_XImImnSGhjJ3Q',
    appId: '1:856901465837:web:424e94311556f90c713ee4',
    messagingSenderId: '856901465837',
    projectId: 'vamonessa-bdcdc',
    authDomain: 'vamonessa-bdcdc.firebaseapp.com',
    databaseURL: 'https://vamonessa-bdcdc-default-rtdb.firebaseio.com',
    storageBucket: 'vamonessa-bdcdc.firebasestorage.app',
    measurementId: 'G-88KK0B96HW',
  );

}